// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Clerk.Net.Client.Models {
    public enum AllowlistIdentifier_identifier_type {
        [EnumMember(Value = "email_address")]
        Email_address,
        [EnumMember(Value = "phone_number")]
        Phone_number,
        [EnumMember(Value = "web3_wallet")]
        Web3_wallet,
    }
}
