// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Clerk.Net.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    /// <summary>String representing the object&apos;s type. Objects of the same type share the same value.</summary>
    public enum AllowlistIdentifier_object
    {
        [EnumMember(Value = "allowlist_identifier")]
        #pragma warning disable CS1591
        Allowlist_identifier,
        #pragma warning restore CS1591
    }
}
