// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Clerk.Net.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
    #pragma warning disable CS1591
    public enum AllowlistIdentifier_identifier_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "email_address")]
        #pragma warning disable CS1591
        Email_address,
        #pragma warning restore CS1591
        [EnumMember(Value = "phone_number")]
        #pragma warning disable CS1591
        Phone_number,
        #pragma warning restore CS1591
        [EnumMember(Value = "web3_wallet")]
        #pragma warning disable CS1591
        Web3_wallet,
        #pragma warning restore CS1591
    }
}
