// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Clerk.Net.Client.Models
{
    /// <summary>String representing the object&apos;s type. Objects of the same type share the same value.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AWSCredential_object
    {
        [EnumMember(Value = "aws_credential")]
        #pragma warning disable CS1591
        Aws_credential,
        #pragma warning restore CS1591
    }
}
