// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace Clerk.Net.Client.Models {
    public class OAuthApplication : IAdditionalDataHolder, IParsable 
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The authorize_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AuthorizeUrl { get; set; }
#nullable restore
#else
        public string AuthorizeUrl { get; set; }
#endif
        /// <summary>The callback_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CallbackUrl { get; set; }
#nullable restore
#else
        public string CallbackUrl { get; set; }
#endif
        /// <summary>The client_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClientId { get; set; }
#nullable restore
#else
        public string ClientId { get; set; }
#endif
        /// <summary>Unix timestamp of creation.</summary>
        public long? CreatedAt { get; set; }
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The instance_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InstanceId { get; set; }
#nullable restore
#else
        public string InstanceId { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The object property</summary>
        public OAuthApplication_object? Object { get; set; }
        /// <summary>The public property</summary>
        public bool? Public { get; set; }
        /// <summary>The scopes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Scopes { get; set; }
#nullable restore
#else
        public string Scopes { get; set; }
#endif
        /// <summary>The token_fetch_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TokenFetchUrl { get; set; }
#nullable restore
#else
        public string TokenFetchUrl { get; set; }
#endif
        /// <summary>Unix timestamp of last update.</summary>
        public long? UpdatedAt { get; set; }
        /// <summary>The user_info_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserInfoUrl { get; set; }
#nullable restore
#else
        public string UserInfoUrl { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="OAuthApplication"/> and sets the default values.
        /// </summary>
        public OAuthApplication()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="OAuthApplication"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static OAuthApplication CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new OAuthApplication();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                {"authorize_url", n => { AuthorizeUrl = n.GetStringValue(); } },
                {"callback_url", n => { CallbackUrl = n.GetStringValue(); } },
                {"client_id", n => { ClientId = n.GetStringValue(); } },
                {"created_at", n => { CreatedAt = n.GetLongValue(); } },
                {"id", n => { Id = n.GetStringValue(); } },
                {"instance_id", n => { InstanceId = n.GetStringValue(); } },
                {"name", n => { Name = n.GetStringValue(); } },
                {"object", n => { Object = n.GetEnumValue<OAuthApplication_object>(); } },
                {"public", n => { Public = n.GetBoolValue(); } },
                {"scopes", n => { Scopes = n.GetStringValue(); } },
                {"token_fetch_url", n => { TokenFetchUrl = n.GetStringValue(); } },
                {"updated_at", n => { UpdatedAt = n.GetLongValue(); } },
                {"user_info_url", n => { UserInfoUrl = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("authorize_url", AuthorizeUrl);
            writer.WriteStringValue("callback_url", CallbackUrl);
            writer.WriteStringValue("client_id", ClientId);
            writer.WriteLongValue("created_at", CreatedAt);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("instance_id", InstanceId);
            writer.WriteStringValue("name", Name);
            writer.WriteEnumValue<OAuthApplication_object>("object", Object);
            writer.WriteBoolValue("public", Public);
            writer.WriteStringValue("scopes", Scopes);
            writer.WriteStringValue("token_fetch_url", TokenFetchUrl);
            writer.WriteLongValue("updated_at", UpdatedAt);
            writer.WriteStringValue("user_info_url", UserInfoUrl);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
