// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Clerk.Net.Client.Models {
    public enum OrganizationInvitation_role {
        [EnumMember(Value = "admin")]
        Admin,
        [EnumMember(Value = "basic_member")]
        Basic_member,
    }
}
