// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Clerk.Net.Client.Models {
    public enum OrganizationSettings_domains_enrollment_modes {
        [EnumMember(Value = "manual_invitation")]
        Manual_invitation,
        [EnumMember(Value = "automatic_invitation")]
        Automatic_invitation,
        [EnumMember(Value = "automatic_suggestion")]
        Automatic_suggestion,
    }
}
