// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Clerk.Net.Client.Models {
    public enum OTP_status
    {
        [EnumMember(Value = "unverified")]
        Unverified,
        [EnumMember(Value = "verified")]
        Verified,
        [EnumMember(Value = "failed")]
        Failed,
        [EnumMember(Value = "expired")]
        Expired,
    }
}
