// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Clerk.Net.Client.Models {
    public enum OTP_strategy {
        [EnumMember(Value = "phone_code")]
        Phone_code,
        [EnumMember(Value = "email_code")]
        Email_code,
        [EnumMember(Value = "reset_password_email_code")]
        Reset_password_email_code,
    }
}
