// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Clerk.Net.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.17.0")]
    #pragma warning disable CS1591
    public enum SignInToken_object
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "sign_in_token")]
        #pragma warning disable CS1591
        Sign_in_token,
        #pragma warning restore CS1591
    }
}
