// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Clerk.Net.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum SignUpVerification_next_action
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "needs_prepare")]
        #pragma warning disable CS1591
        Needs_prepare,
        #pragma warning restore CS1591
        [EnumMember(Value = "needs_attempt")]
        #pragma warning disable CS1591
        Needs_attempt,
        #pragma warning restore CS1591
    }
}
