// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Clerk.Net.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
    #pragma warning disable CS1591
    public enum Web3Signature_strategy
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "web3_metamask_signature")]
        #pragma warning disable CS1591
        Web3_metamask_signature,
        #pragma warning restore CS1591
    }
}
