// <auto-generated/>
#pragma warning disable CS0618
using Clerk.Net.Client.Webhooks.Svix;
using Clerk.Net.Client.Webhooks.Svix_url;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Clerk.Net.Client.Webhooks
{
    /// <summary>
    /// Builds and executes requests for operations under \webhooks
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
    public partial class WebhooksRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The svix property</summary>
        public global::Clerk.Net.Client.Webhooks.Svix.SvixRequestBuilder Svix
        {
            get => new global::Clerk.Net.Client.Webhooks.Svix.SvixRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The svix_url property</summary>
        public global::Clerk.Net.Client.Webhooks.Svix_url.Svix_urlRequestBuilder Svix_url
        {
            get => new global::Clerk.Net.Client.Webhooks.Svix_url.Svix_urlRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Clerk.Net.Client.Webhooks.WebhooksRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WebhooksRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/webhooks", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Clerk.Net.Client.Webhooks.WebhooksRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WebhooksRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/webhooks", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
