// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Clerk.Net.Client.Sessions.Item.Tokens.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    #pragma warning disable CS1591
    public enum WithTemplate_namePostResponse_object
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "token")]
        #pragma warning disable CS1591
        Token,
        #pragma warning restore CS1591
    }
}
