// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Clerk.Net.Client.Users.Item.Verify_totp
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Verify_totpPostResponse_code_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "totp")]
        #pragma warning disable CS1591
        Totp,
        #pragma warning restore CS1591
        [EnumMember(Value = "backup_code")]
        #pragma warning disable CS1591
        Backup_code,
        #pragma warning restore CS1591
    }
}
