// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Clerk.Net.Client.Invitations.Bulk
{
    /// <summary>The slug of the email template to use for the invitation email.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Bulk_template_slug
    {
        [EnumMember(Value = "invitation")]
        #pragma warning disable CS1591
        Invitation,
        #pragma warning restore CS1591
        [EnumMember(Value = "waitlist_invitation")]
        #pragma warning disable CS1591
        Waitlist_invitation,
        #pragma warning restore CS1591
    }
}
