// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Clerk.Net.Client.Beta_features.Instance_settings
{
    /// <summary>String representing the object&apos;s type. Objects of the same type share the same value.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.17.0")]
    public enum Instance_settingsPatchResponse_object
    {
        [EnumMember(Value = "instance_settings")]
        #pragma warning disable CS1591
        Instance_settings,
        #pragma warning restore CS1591
    }
}
