// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Clerk.Net.Client.Saml_connections
{
    /// <summary>The IdP provider of the connection.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
    public enum Saml_connectionsPostRequestBody_provider
    {
        [EnumMember(Value = "saml_custom")]
        #pragma warning disable CS1591
        Saml_custom,
        #pragma warning restore CS1591
        [EnumMember(Value = "saml_okta")]
        #pragma warning disable CS1591
        Saml_okta,
        #pragma warning restore CS1591
        [EnumMember(Value = "saml_google")]
        #pragma warning disable CS1591
        Saml_google,
        #pragma warning restore CS1591
        [EnumMember(Value = "saml_microsoft")]
        #pragma warning disable CS1591
        Saml_microsoft,
        #pragma warning restore CS1591
    }
}
