// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Clerk.Net.Client.Invitations.Item.Revoke
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
    #pragma warning disable CS1591
    public enum Invitation_status
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "revoked")]
        #pragma warning disable CS1591
        Revoked,
        #pragma warning restore CS1591
    }
}
